image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:

  - java -jar ./artefacts/app-card-delivery.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true
  - -Dselenide.browser=firefox